options:
  ruby-version:
    default: '2.2.0'
    description: |
      Ruby Version to use for your application.
    type: string
  ruby-mirror:
    default: 'https://cache.ruby-lang.org/pub/ruby'
    description: |
      Default mirror to pull Ruby from, choose one closest to your datacenter.
  app-path:
    type: string
    default: '/srv/app'
    description: |
      The default location of your Ruby application, defaults /srv/app
